replicaCount: 1

kind: Deployment

image:
  repository: harbor.local.fintech23.xyz/splitbill/split-bill-user-service
  pullPolicy: Always
  tag: "qa"

imagePullSecrets:
  - harbor-local-fintech23-xyz-image-pull-secrets

config:
  HOSTNAME: "split-bill-user-service"
  DISCOVERY_SERVER_URI: "http://bs23-ib-rt-discovery-service-statefulset-0.bs23-ib-rt-discovery-service-hl-service:8761/eureka/,http://bs23-ib-rt-discovery-service-statefulset-1.bs23-ib-rt-discovery-service-hl-service:8761/eureka/,http://bs23-ib-rt-discovery-service-statefulset-2.bs23-ib-rt-discovery-service-hl-service:8761/eureka/"
  SERVER_PORT: "8080"
  SPRING_PROFILES_ACTIVE: "k8s"
  DEV_HOME: "/tmp/logs"
  LOG_MAX_FILESIZE: "100MB"
  LOG_MAX_FILECOUNT: "6"
  TZ: "Asia/Dhaka"
  OTEL_JAVAAGENT_ENABLED: "true"
  OTEL_SERVICE_NAME: "split-bill-user-service"
  OTEL_TRACES_SAMPLER: "always_on"
  OTEL_TRACES_EXPORTER: "otlp"
  OTEL_METRICS_EXPORTER: "otlp"
  OTEL_LOGS_EXPORTER: "otlp"
  OTEL_EXPORTER_OTLP_PROTOCOL: "grpc"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://otelcollector-collector:4317"
  MASTER_DB_URL: "jdbc:postgresql://splitbill-psql:5432/splitbill?currentSchema=user_service;encrypt=false;trustServerCertificate=false"
  MASTER_DB_USERNAME: "zalando"
  MASTER_DB_PASSWORD: "HmvlxpneZNFsOiDOUt4tZLiG5T8NUCOzdhoV5K9TroDgxAxVFyDjfxjKEwzS4MFl"
  MASTER_DB_MAX_POOL_SIZE: "50"
  MASTER_DB_MIN_IDLE: "10"
  MASTER_DB_CONNECTION_TIMEOUT: "30000"
  MASTER_DB_IDLE_TIMEOUT: "600000"
  MASTER_DB_MAX_LIFETIME: "1800000"
  MASTER_DB_POOL_NAME: "UserMasterHikariCP"
  MASTER_DB_VALIDATION_TIMEOUT: "5000"
  MASTER_DB_LEAK_DETECTION_THRESHOLD: "60000"

  # Slave Database
  SLAVE_DB_URL: "jdbc:postgresql://splitbill-psql:5432/splitbill?currentSchema=user_service;encrypt=false;trustServerCertificate=false"
  SLAVE_DB_USERNAME: "zalando"
  SLAVE_DB_PASSWORD: "HmvlxpneZNFsOiDOUt4tZLiG5T8NUCOzdhoV5K9TroDgxAxVFyDjfxjKEwzS4MFl"
  SLAVE_DB_MAX_POOL_SIZE: "50"
  SLAVE_DB_MIN_IDLE: "10"
  SLAVE_DB_CONNECTION_TIMEOUT: "30000"
  SLAVE_DB_IDLE_TIMEOUT: "600000"
  SLAVE_DB_MAX_LIFETIME: "1800000"
  SLAVE_DB_POOL_NAME: "UserSlaveHikariCP"
  SLAVE_DB_VALIDATION_TIMEOUT: "5000"
  SLAVE_DB_LEAK_DETECTION_THRESHOLD: "60000"

  # Redis
  REDIS_HOST: "rfrm-splitbill-redis"
  REDIS_PORT: "6379"
  REDIS_DATABASE_INDEX: "0"
  REDIS_POOL_MAX_CONNECTION: "30"
  REDIS_POOL_MAX_IDLE_CONNECTION: "10"
  REDIS_POOL_MIN_IDLE_CONNECTION: "0"

  # Logging
  LOGGING_CONFIG: "classpath:log/logback-k8s.xml"

  # External Services
  PAYMENT_SERVICE_BASE_URL: "http://localhost:9014"
  REMITTANCE_SERVICE_BASE_URL: "localhost:90"


service:
  - name: api
    type: ClusterIP
    targetPort: 8080
    port: 80

liveness:
  enabled: true
  method: http
  service: api
  path: "/actuator/health/liveness"
  initialDelaySeconds: 90
  periodSeconds: 10

readiness:
  enabled: true
  method: http
  service: api
  path: "/actuator/health/readiness"
  initialDelaySeconds: 90
  periodSeconds: 60

resources:
  requests:
    memory: "500Mi"
    cpu: "1"
  limits:
    memory: "2Gi"
    cpu: "2"
